import test,{before,after,beforeEach} from "node:test";import assert from "node:assert/strict";import {resolve} from "node:path";
import {PostgresPersistence,PersistenceConflict,applyMigrations} from "../../packages/persistence-postgres/src/index.js";
const url=process.env.DATABASE_URL;const skip=!url;let db:PostgresPersistence;
before(async()=>{if(skip)return;db=new PostgresPersistence({connectionString:url!,applicationName:"ssw-sera-test"});await applyMigrations(db.pool,resolve("db/migrations"));});
beforeEach(async()=>{if(skip)return;await db.pool.query("TRUNCATE ssw.event_inbox,ssw.event_outbox,ssw.execution_state,ssw.mandate_usage,ssw.replay_claim,ssw.idempotency_claim,ssw.domain_record RESTART IDENTITY");});
after(async()=>{if(!skip)await db.close();});

test("optimistic record writes reject stale versions",{skip},async()=>{const s=db.session();assert.equal(await s.saveRecord({ownerService:"device",recordType:"device",recordId:"d1",status:"TRUSTED",state:{x:1},stateHash:"sha256:a"}),1);assert.equal(await s.saveRecord({ownerService:"device",recordType:"device",recordId:"d1",status:"LIMITED",state:{x:2},stateHash:"sha256:b",expectedVersion:1}),2);await assert.rejects(()=>s.saveRecord({ownerService:"device",recordType:"device",recordId:"d1",status:"TRUSTED",state:{x:3},stateHash:"sha256:c",expectedVersion:1}),(e:any)=>e instanceof PersistenceConflict&&e.code==="OPTIMISTIC_CONCURRENCY_CONFLICT");});
test("idempotency distinguishes identical retry and conflict",{skip},async()=>{const s=db.session();assert.equal(await s.claimIdempotency({ownerService:"signing",key:"idem-1",requestHash:"sha256:a"}),"FRESH");assert.equal(await s.claimIdempotency({ownerService:"signing",key:"idem-1",requestHash:"sha256:a"}),"IDENTICAL_RETRY");assert.equal(await s.claimIdempotency({ownerService:"signing",key:"idem-1",requestHash:"sha256:b"}),"CONFLICT");});
test("replay claims persist single-use REV consumption",{skip},async()=>{const s=db.session();assert.equal(await s.claimReplay({ownerService:"signing",replayToken:"r1",requestHash:"sha256:a",revDecisionId:"rev:1"}),"FRESH");assert.equal(await s.claimReplay({ownerService:"signing",replayToken:"r2",requestHash:"sha256:a",revDecisionId:"rev:1"}),"REPLAY");await s.consumeReplay({ownerService:"signing",replayToken:"r1"});});
test("mandate usage reservation is atomic and bounded",{skip},async()=>{await db.transaction(async s=>{const r=await s.reserveMandateUsage({mandateId:"m1",assetId:"USDC",amountAtomic:"5",maxActionCount:2,maxCumulativeAtomic:"10"});assert.equal(String(r.cumulative_atomic),"5");});await db.transaction(async s=>{await s.reserveMandateUsage({mandateId:"m1",assetId:"USDC",amountAtomic:"5",maxActionCount:2,maxCumulativeAtomic:"10"});});await assert.rejects(()=>db.transaction(s=>s.reserveMandateUsage({mandateId:"m1",assetId:"USDC",amountAtomic:"1",maxActionCount:2,maxCumulativeAtomic:"10"})),/MANDATE_ACTION_COUNT_EXCEEDED/);});
test("outbox claim and inbox deduplication are durable",{skip},async()=>{const s=db.session();const eventId="11111111-1111-4111-8111-111111111111";await s.enqueueOutbox({eventId,ownerService:"execution",topic:"EXECUTION.SUBMITTED",partitionKey:"holder:alice",payload:{ok:true}});const claimed=await s.claimOutbox({limit:10,leaseSeconds:30});assert.equal(claimed.length,1);await s.markOutboxDelivered(eventId);assert.equal(await s.acceptInbox({consumerService:"sael",eventId,payloadHash:"sha256:a"}),"FRESH");assert.equal(await s.acceptInbox({consumerService:"sael",eventId,payloadHash:"sha256:a"}),"IDENTICAL_RETRY");assert.equal(await s.acceptInbox({consumerService:"sael",eventId,payloadHash:"sha256:b"}),"CONFLICT");});
