import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";
import {buildPaymentSendAction} from "../../packages/action-contract-builder/src/index.js";
import {createReviewRecord,createApprovalRecord,applyApprovalToAction} from "../../packages/approval-runtime/src/index.js";
async function setup(){const intent=JSON.parse(await readFile(new URL("../fixtures/resolved-intent.payment-send.valid.json",import.meta.url),"utf8"));const b=buildPaymentSendAction(intent,{actionId:"88888888-8888-4888-8888-888888888888",saelCorrelationId:"99999999-9999-4999-8999-999999999999",idempotencyKey:"idem-test-001",replayToken:"replay-test-001",createdAt:"2026-09-19T20:00:00Z",expiresAt:"2026-09-19T20:20:00Z"});if(b.status!=="BUILT")throw new Error();const review=createReviewRecord({action:b.actionContract,materialTermsHash:b.materialTermsHash,reviewId:"11111111-1111-4111-8111-111111111111",presentationRef:"presentation:1",reviewedAt:"2026-09-19T20:04:00Z"});return{b,review};}
function auth(x:any,purpose="ACTION_APPROVAL",level="AL2"){return{schema:"ssw.authentication-evidence.v1",auth_id:"22222222-2222-4222-8222-222222222222",purpose,method:"DEVICE_BIOMETRIC",assurance_level:level,status:"PASS",holder_did:x.b.actionContract.principal.holder_did,action_id:x.b.actionContract.action_id,action_version:x.b.actionContract.version,material_terms_hash:x.b.materialTermsHash,device_id:x.b.actionContract.principal.device_id,runtime_id:x.b.actionContract.principal.sera_runtime_id,challenge_ref:"challenge:approval:1",verifier_identity:"auth-service:soulverse",issued_at:"2026-09-19T20:04:10Z",expires_at:"2026-09-19T20:06:00Z",integrity:{evidence_hash:"sha256:"+"a".repeat(64),signature_ref:"signature:auth:1"}};}
function approve(x:any,a:any){return createApprovalRecord({action:x.b.actionContract,materialTermsHash:x.b.materialTermsHash,review:x.review,authentication:a,approvalId:"33333333-3333-4333-8333-333333333333",approvedAt:"2026-09-19T20:05:00Z",expiresAt:"2026-09-19T20:10:00Z",approvalHash:"sha256:"+"b".repeat(64),approvalSignatureRef:"signature:approval:1"});}

test("exact review and approval-purpose authentication create approval",async()=>{const x=await setup();assert.equal(approve(x,auth(x)).status,"APPROVED");});
test("material hash mismatch blocks",async()=>{const x=await setup();const a=auth(x);a.material_terms_hash="sha256:"+"f".repeat(64);assert.throws(()=>approve(x,a));});
test("action version mismatch blocks",async()=>{const x=await setup();const a=auth(x);a.action_version=2;assert.throws(()=>approve(x,a));});
test("wrong holder blocks",async()=>{const x=await setup();const a=auth(x);a.holder_did="did:soul:other";assert.throws(()=>approve(x,a));});
test("wrong device blocks",async()=>{const x=await setup();const a=auth(x);a.device_id="device:other";assert.throws(()=>approve(x,a));});
test("wrong runtime blocks",async()=>{const x=await setup();const a=auth(x);a.runtime_id="sera-runtime:other";assert.throws(()=>approve(x,a));});
test("expired authentication blocks",async()=>{const x=await setup();const a=auth(x);a.expires_at="2026-09-19T20:04:59Z";assert.throws(()=>approve(x,a));});
test("RECOVERY authentication cannot approve",async()=>{const x=await setup();assert.throws(()=>approve(x,auth(x,"RECOVERY")));});
test("REVEAL authentication cannot approve",async()=>{const x=await setup();assert.throws(()=>approve(x,auth(x,"REVEAL")));});
test("AL1 is insufficient for R3 payment",async()=>{const x=await setup();assert.throws(()=>approve(x,auth(x,"ACTION_APPROVAL","AL1")));});
test("approval enriches copy and preserves NOT_READY",async()=>{const x=await setup();const ap=approve(x,auth(x));const next=applyApprovalToAction(x.b.actionContract,ap,x.review);assert.equal(x.b.actionContract.approval.status,"REQUIRED");assert.equal(next.approval.status,"APPROVED");assert.equal(next.approval.approved_terms_hash,x.b.materialTermsHash);assert.equal(next.execution.status,"NOT_READY");});
test("approval cannot be reused after material change",async()=>{const x=await setup();const ap=approve(x,auth(x));const changed=structuredClone(x.b.actionContract);(changed.material_terms as any).amount.atomic="5000001";assert.equal(ap.material_terms_hash,x.b.materialTermsHash);assert.notDeepEqual(changed.material_terms,x.b.actionContract.material_terms);});
