import test from "node:test";import assert from "node:assert/strict";
import {generateKeyPairSync,sign} from "node:crypto";
import {computeDecisionHash,verifyDecisionIntegrity,StaticDecisionKeyResolver,CircuitBreaker,ControlServiceError,ProductionTrustProtocolTransport,type DecisionPersistence,type SecureJsonClient} from "../../packages/control-service-client/src/index.js";

function signedDecision(){
 const {publicKey,privateKey}=generateKeyPairSync("ed25519");const decision:any={schema:"ssw.trust-protocol-decision.v1",decision_id:"11111111-1111-4111-8111-111111111111",request_id:"22222222-2222-4222-8222-222222222222",action_id:"33333333-3333-4333-8333-333333333333",action_version:1,material_terms_hash:"sha256:"+"a".repeat(64),status:"PASS",reason_codes:[],principal:{holder_did:"did:soul:holder-alice",sera_agent_did:"did:soul:agent:sera-alice"},runtime:{device_id:"device:phone-001",sera_runtime_id:"sera-runtime:phone-001"},authority_class:"A2",risk_class:"R3",policy_version:"1",service_identity:"trust-service:soulverse-prod",issued_at:"2026-09-19T23:00:00Z",expires_at:"2026-09-19T23:10:00Z",integrity:{decision_hash:"",signature_ref:""}};
 decision.integrity.decision_hash=computeDecisionHash("TRUST",decision);const digest=Buffer.from(decision.integrity.decision_hash.slice(7),"hex");decision.integrity.signature_ref="ed25519:k1:"+sign(null,digest,privateKey).toString("base64url");
 return{decision,publicKey};
}
test("valid Ed25519 decision integrity verifies",async()=>{const x=signedDecision();const resolver=new StaticDecisionKeyResolver(new Map([["trust-service:soulverse-prod:k1",x.publicKey]]));const v=await verifyDecisionIntegrity({kind:"TRUST",decision:x.decision,expectedServiceIdentity:"trust-service:soulverse-prod",keyResolver:resolver});assert.equal(v.keyId,"k1");});
test("tampered decision hash fails",async()=>{const x=signedDecision();x.decision.status="FAIL";const resolver=new StaticDecisionKeyResolver(new Map([["trust-service:soulverse-prod:k1",x.publicKey]]));await assert.rejects(()=>verifyDecisionIntegrity({kind:"TRUST",decision:x.decision,expectedServiceIdentity:"trust-service:soulverse-prod",keyResolver:resolver}),/DECISION_HASH_MISMATCH/);});
test("unknown signing key fails",async()=>{const x=signedDecision();await assert.rejects(()=>verifyDecisionIntegrity({kind:"TRUST",decision:x.decision,expectedServiceIdentity:"trust-service:soulverse-prod",keyResolver:new StaticDecisionKeyResolver(new Map())}),/DECISION_SIGNING_KEY_UNKNOWN/);});
test("circuit opens after threshold and later resets",()=>{let now=0;const b=new CircuitBreaker(2,100,()=>now);b.failure();assert.equal(b.state,"CLOSED");b.failure();assert.equal(b.state,"OPEN");assert.throws(()=>b.before(),/CONTROL_SERVICE_CIRCUIT_OPEN/);now=101;b.before();assert.equal(b.state,"CLOSED");});
test("production transport retries retryable network error then verifies signed decision",async()=>{const x=signedDecision();let calls=0;const client:SecureJsonClient={post:async()=>{calls++;if(calls===1)throw new ControlServiceError("CONTROL_SERVICE_TIMEOUT",true);return x.decision;}};const persistence:DecisionPersistence={claimRequest:async()=>"FRESH",storeDecision:async()=>{}};const transport=new ProductionTrustProtocolTransport({endpoint:"https://trust.internal/v1/evaluate",expectedServiceIdentity:"trust-service:soulverse-prod",keyResolver:new StaticDecisionKeyResolver(new Map([["trust-service:soulverse-prod:k1",x.publicKey]])),client,persistence,maxAttempts:2,circuitBreaker:new CircuitBreaker(3,1000)});const request:any={schema:"ssw.trust-protocol-request.v1",request_id:x.decision.request_id,action_id:x.decision.action_id,action_version:1,material_terms_hash:x.decision.material_terms_hash,principal:x.decision.principal,runtime:{device_id:x.decision.runtime.device_id,sera_runtime_id:x.decision.runtime.sera_runtime_id,eligibility_decision_ref:"44444444-4444-4444-8444-444444444444"},authority:{class:"A2",approval_ref:null,mandate_ref:null,mandate_evaluation_ref:null,mandate_terms_hash:null},risk:{class:"R3",reason_codes:[]},policy:{decision_ref:"55555555-5555-4555-8555-555555555555",policy_ref:"policy:1",policy_version:"1"},context_refs:[],issued_at:"2026-09-19T23:00:00Z",expires_at:"2026-09-19T23:05:00Z"};const d=await transport.evaluate(request);assert.equal(d.status,"PASS");assert.equal(calls,2);});
test("request idempotency conflict blocks network call",async()=>{let called=false;const x=signedDecision();const transport=new ProductionTrustProtocolTransport({endpoint:"https://trust.internal/v1/evaluate",expectedServiceIdentity:"trust-service:soulverse-prod",keyResolver:new StaticDecisionKeyResolver(new Map([["trust-service:soulverse-prod:k1",x.publicKey]])),client:{post:async()=>{called=true;return x.decision;}},persistence:{claimRequest:async()=>"CONFLICT",storeDecision:async()=>{}},maxAttempts:1});const request:any={request_id:"22222222-2222-4222-8222-222222222222",expires_at:"2026-09-19T23:05:00Z"};await assert.rejects(()=>transport.evaluate(request),/CONTROL_REQUEST_IDEMPOTENCY_CONFLICT/);assert.equal(called,false);});
