import test from "node:test";import assert from "node:assert/strict";
import {buildCredentialDisclosurePlan,CredentialPresentationRuntime,CredentialRuntimeError,hashCredentialPresentationRequest,selectCredentialForRequest,type CredentialPresentationRequest,type CredentialDescriptor} from "../../packages/ssw-capability-adapters/src/credential-runtime.js";

const now="2026-09-19T22:00:00Z";
const request:CredentialPresentationRequest={requestId:"req-1",holderDid:"did:soul:kavitha",seraAgentDid:"did:soul:agent:sera",verifierCanonicalId:"did:example:verifier",protocol:"OPENID4VP",nonce:"n-1",domain:"verifier.example",purpose:"age verification",requestedClaims:["age_over_18"],requestedCredentialTypes:["AgeCredential"],issuedAt:"2026-09-19T21:59:00Z",expiresAt:"2026-09-19T22:10:00Z"};
const credential:CredentialDescriptor={credentialRef:"cred:age:1",credentialType:"AgeCredential",issuerRef:"did:example:issuer",format:"SD_JWT_VC",status:"ACTIVE",claimNames:["birth_date","age_over_18"],claimSensitivity:{birth_date:"HIGH",age_over_18:"LOW"},validUntil:"2027-01-01T00:00:00Z"};

test("credential request hash is stable across requested claim ordering",()=>{const a=hashCredentialPresentationRequest({...request,requestedClaims:["age_over_18","country"]});const b=hashCredentialPresentationRequest({...request,requestedClaims:["country","age_over_18"]});assert.equal(a,b);});
test("credential selection requires exact claim coverage and active state",()=>{assert.equal(selectCredentialForRequest(request,[credential],now).credentialRef,"cred:age:1");assert.throws(()=>selectCredentialForRequest(request,[{...credential,status:"REVOKED"}],now),(e:any)=>e.code==="NO_ELIGIBLE_CREDENTIAL");});
test("ambiguous credentials fail closed",()=>{assert.throws(()=>selectCredentialForRequest(request,[credential,{...credential,credentialRef:"cred:age:2"}],now),(e:any)=>e.code==="AMBIGUOUS_CREDENTIAL");});
test("disclosure plan contains claim names but no credential values",()=>{const p=buildCredentialDisclosurePlan({request,credential,now,planId:"plan-1"});assert.deepEqual(p.disclosedClaims,["age_over_18"]);assert.equal(p.sensitivity,"LOW");assert.equal(p.authorityEffect,"NONE");assert.equal("birth_date" in (p as any),false);});
test("proof generation fails without required Trust and REV evidence",async()=>{let called=false;const runtime=new CredentialPresentationRuntime({generate:async()=>{called=true;return{proofRef:"p",presentationTokenRef:"pt",format:"SD_JWT_VC"};},present:async()=>({receiptRef:"r",presentedAt:now})});const plan=buildCredentialDisclosurePlan({request,credential,now,planId:"plan-1"});await assert.rejects(runtime.generateProof({request,plan,control:{requestHash:plan.requestHash,reviewRef:"review",authorizationRef:"auth",trustDecisionRef:null,revDecisionRef:null,trustSatisfied:false,revSatisfied:false,validUntil:"2026-09-19T22:05:00Z"},now}),(e:any)=>e instanceof CredentialRuntimeError&&e.code==="TRUST_REQUIRED");assert.equal(called,false);});
test("authorized proof generation and presentation preserve exact verifier/request binding",async()=>{const calls:any[]=[];const runtime=new CredentialPresentationRuntime({generate:async i=>{calls.push(["generate",i]);return{proofRef:"proof:1",presentationTokenRef:"token:1",format:i.format};},present:async i=>{calls.push(["present",i]);return{receiptRef:"receipt:1",presentedAt:now};}});const plan=buildCredentialDisclosurePlan({request,credential,now,planId:"plan-1"});const control={requestHash:plan.requestHash,reviewRef:"review:1",authorizationRef:"approval:1",trustDecisionRef:"trust:1",revDecisionRef:"rev:1",trustSatisfied:true,revSatisfied:true,validUntil:"2026-09-19T22:05:00Z"};const proof=await runtime.generateProof({request,plan,control,now});const receipt=await runtime.present({request,plan,control,proof,now});assert.equal(receipt.receiptRef,"receipt:1");assert.equal(calls[0][1].verifierCanonicalId,"did:example:verifier");assert.equal(calls[1][1].requestHash,plan.requestHash);});
