import test from "node:test";import assert from "node:assert/strict";
import {sanitizeExternalText,normalizeNewsRecord,normalizeProfessionalRecord,normalizeAssetRiskRecord,NewsContextSource,ProfessionalContextSource,AssetRiskContextSource} from "../../packages/external-context-adapters/src/index.js";
test("external text sanitation removes markup/control characters but retains untrusted role",()=>{const s=sanitizeExternalText("<b>Protocol X</b>\u0000 update <script>bad()</script>");assert.equal(s,"Protocol X update");});
test("news is advisory non-authority context",()=>{const r:any=normalizeNewsRecord({sourceId:"news",sourceRef:"source:1",subject:{type:"protocol",id:"x"},headline:"Incident",excerpt:"Reported event",entityRefs:["protocol:x"],confidence:.8,veracity:"UNCONFIRMED",publishedAt:"2026-09-19T21:00:00Z",validUntil:null},"2026-09-19T21:01:00Z","11111111-1111-4111-8111-111111111111");assert.equal(r.content_role,"UNTRUSTED_EXTERNAL_TEXT");assert.equal(r.authority_effect,"NONE");assert.equal(r.identity_authority,false);});
test("professional profile never becomes identity authority",()=>{const r:any=normalizeProfessionalRecord({sourceId:"professional",sourceRef:"profile:1",subject:{type:"person",id:"alice"},displayName:"Alice",organization:"Example",role:"CEO",entityRefs:["person:alice"],confidence:.95,veracity:"HIGH_CONFIDENCE",observedAt:"2026-09-19T21:00:00Z",validUntil:null,platformVerified:true},"2026-09-19T21:01:00Z","22222222-2222-4222-8222-222222222222");assert.equal(r.data.platform_verified,true);assert.equal(r.data.identity_authority,false);assert.equal(r.identity_authority,false);});
test("asset risk is structured security input with no authority effect",()=>{const r:any=normalizeAssetRiskRecord({sourceId:"spam-filter",sourceRef:"risk:1",assetId:"0xabc",chainId:"eip155:137",status:"KNOWN_MALICIOUS",reasonCodes:["KNOWN_SPAM"],evidenceRefs:["evidence:1"],confidence:.99,veracity:"CONFIRMED",observedAt:"2026-09-19T21:00:00Z",validUntil:null},"2026-09-19T21:01:00Z","33333333-3333-4333-8333-333333333333");assert.equal(r.content_role,"STRUCTURED_RISK_SIGNAL");assert.equal(r.authority_effect,"NONE");});
test("ContextSource adapters preserve provenance classes",async()=>{const now="2026-09-19T21:01:00Z";const news=new NewsContextSource({search:async()=>[{sourceId:"n",sourceRef:"n:1",subject:{type:"asset",id:"a"},headline:"h",excerpt:"e",entityRefs:[],confidence:.7,veracity:"UNCONFIRMED",publishedAt:now,validUntil:null}]},"asset a");const n=await news.fetch({holderDid:"did:soul:h",seraAgentDid:"did:soul:agent:s",contextKey:"news_context",purpose:"brief",now});assert.equal(n?.sourceType,"EXTERNAL");assert.equal(n?.provenance,"EXTERNAL_IMPORTED");
const pro=new ProfessionalContextSource({lookup:async()=>({sourceId:"p",sourceRef:"p:1",subject:{type:"person",id:"x"},displayName:"X",organization:null,role:null,entityRefs:[],confidence:.8,veracity:"UNCONFIRMED",observedAt:now,validUntil:null,platformVerified:false})},"person:x");assert.equal((await pro.fetch({holderDid:"did:soul:h",seraAgentDid:"did:soul:agent:s",contextKey:"professional_context",purpose:"resolve",now}))?.sourceType,"EXTERNAL");
const risk=new AssetRiskContextSource({get:async()=>({sourceId:"r",sourceRef:"r:1",assetId:"a",chainId:"eip155:1",status:"SUSPICIOUS",reasonCodes:["SUSPICIOUS"],evidenceRefs:[],confidence:.9,veracity:"CONFIRMED",observedAt:now,validUntil:null})},"a","eip155:1");const rr=await risk.fetch({holderDid:"did:soul:h",seraAgentDid:"did:soul:agent:s",contextKey:"asset_risk",purpose:"prepare",now});assert.equal(rr?.sourceType,"SECURITY");assert.equal(rr?.externalTransmissionAllowed,false);});
