import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";
import {buildPaymentSendAction} from "../../packages/action-contract-builder/src/index.js";import {evaluateMandate} from "../../packages/mandate-runtime/src/index.js";import {evaluateDmcl} from "../../packages/dmcl/src/index.js";
async function base(){const intent=JSON.parse(await readFile(new URL("../fixtures/resolved-intent.payment-send.valid.json",import.meta.url),"utf8"));const b=buildPaymentSendAction(intent,{actionId:"88888888-8888-4888-8888-888888888888",saelCorrelationId:"99999999-9999-4999-8999-999999999999",idempotencyKey:"x",replayToken:"y",createdAt:"2026-09-19T16:01:00Z",expiresAt:"2026-09-19T16:06:00Z"});if(b.status!=="BUILT")throw new Error();const m=JSON.parse(await readFile(new URL("../fixtures/mandate.payment-send.a3.valid.json",import.meta.url),"utf8"));const a=structuredClone(b.actionContract);a.authority.class="A3";a.authority.approval_required=false;a.authority.mandate_id=m.mandate_id;return{b,a,m};}
const input=(x:any)=>({action:x.a,mandate:x.m,materialTermsHash:x.b.materialTermsHash,decisionId:"56565656-5656-4565-8565-565656565656",evaluatedAt:"2026-09-19T16:03:00Z",deviceState:"TRUSTED",runtimeClass:"PRIMARY_PHONE"});

test("matching A3 mandate passes",async()=>{const x=await base();assert.equal(evaluateMandate(input(x)).status,"PASS");});
test("wrong holder fails",async()=>{const x=await base();x.m.principal.holder_did="did:soul:other";assert.equal(evaluateMandate(input(x)).status,"IDENTITY_MISMATCH");});
test("expired mandate fails",async()=>{const x=await base();x.m.valid_until="2026-09-19T15:00:00Z";assert.equal(evaluateMandate(input(x)).status,"EXPIRED");});
test("out of scope action fails",async()=>{const x=await base();x.m.scope.action_types=["asset.swap"];assert.equal(evaluateMandate(input(x)).status,"OUT_OF_SCOPE");});
test("amount limit enforced",async()=>{const x=await base();(x.a.material_terms as any).amount.atomic="10000001";assert.equal(evaluateMandate(input(x)).status,"LIMIT_EXCEEDED");});
test("risk ceiling enforced",async()=>{const x=await base();x.a.risk.class="R4";assert.equal(evaluateMandate(input(x)).status,"RISK_EXCEEDED");});
test("device restriction enforced",async()=>{const x=await base();x.m.device_policy.allowed_device_ids=["device:other"];assert.equal(evaluateMandate(input(x)).status,"DEVICE_RUNTIME_MISMATCH");});
test("A4 true condition passes",async()=>{const x=await base();x.a.authority.class="A4";x.m.authority.class="A4";x.m.authority.delegation_type="conditional";x.m.conditions=[{op:"lte",left:{ref:"action.amountAtomic"},right:{literal:"5000000",type:"integer_string"}}];const d=evaluateMandate({...input(x),dmclContext:{action:{amountAtomic:"5000000"},evaluation:{now:"2026-09-19T16:03:00Z"}}});assert.equal(d.status,"PASS");});
test("A4 false condition fails",async()=>{const x=await base();x.a.authority.class="A4";x.m.authority.class="A4";x.m.authority.delegation_type="conditional";x.m.conditions=[{op:"lt",left:{ref:"action.amountAtomic"},right:{literal:"1",type:"integer_string"}}];const d=evaluateMandate({...input(x),dmclContext:{action:{amountAtomic:"5000000"},evaluation:{now:"2026-09-19T16:03:00Z"}}});assert.equal(d.status,"CONDITION_FALSE");});
test("missing DMCL signal is indeterminate",()=>{assert.equal(evaluateDmcl({op:"eq",left:{ref:"signal.price"},right:{literal:"1"}},{evaluation:{now:"2026-09-19T16:03:00Z"}}),"INDETERMINATE");});
test("integer strings compare exactly",()=>{assert.equal(evaluateDmcl({op:"gt",left:{literal:"9007199254740993",type:"integer_string"},right:{literal:"9007199254740992",type:"integer_string"}},{}),"TRUE");});
