import test from "node:test";import assert from "node:assert/strict";import {evaluatePortableKeyRuntime} from "../../packages/signer-runtime/src/portable-key-runtime.js";
const holder="did:soul:holder-alice";const sera="did:soul:agent:sera-alice";const keyRef="keyref:sera:1";
function fixture(){return{
 manifest:{schema:"ssw.portable-key-manifest.v1",manifest_id:"11111111-1111-4111-8111-111111111111",key_ref:keyRef,subject_did:sera,governing_holder_did:holder,key_class:"SERA_AGENT_SIGNING",key_version:3,encrypted_key_cid:"bafybeigdyrztportablekeyobject",encryption_profile:"SOUL-ID-KEY-ENC-1",recovery_policy_ref:"recovery:soulscan",supersedes_manifest_id:null,status:"ACTIVE",created_at:"2026-09-19T20:00:00Z",expires_at:null,integrity:{manifest_hash:"sha256:"+"a".repeat(64),signature_ref:"sig:manifest"}},
 auth:{schema:"ssw.soulscan-recovery-authorization.v1",authorization_id:"22222222-2222-4222-8222-222222222222",recovery_id:"33333333-3333-4333-8333-333333333333",holder_did:holder,sera_agent_did:sera,key_ref:keyRef,purpose:"SIGN",proof_class:"RP2",assurance_level:"RAL4",status:"PASS",issued_at:"2026-09-19T20:00:00Z",expires_at:"2026-09-19T21:00:00Z",verifier_ref:"soulscan:prod",evidence_ref:"recovery-proof:1",reason_codes:[],integrity:{authorization_hash:"sha256:"+"b".repeat(64),signature_ref:"sig:soulscan"}},
 ref:{schema:"ssw.encrypted-key-object-ref.v1",key_ref:keyRef,cid:"bafybeigdyrztportablekeyobject",ciphertext_hash:"sha256:"+"c".repeat(64),encryption_profile:"SOUL-ID-KEY-ENC-1",key_version:3,subject_did:sera,governing_holder_did:holder,created_at:"2026-09-19T20:00:00Z"}
};}
test("SERA portable key recovery passes without device binding",()=>{const x=fixture();const d=evaluatePortableKeyRuntime({manifest:x.manifest,authorization:x.auth,encryptedObjectRef:x.ref,expectedHolderDid:holder,expectedSubjectDid:sera,expectedKeyRef:keyRef,now:"2026-09-19T20:30:00Z",minimumKeyVersion:3});assert.equal(d.status,"PASS");assert.equal(d.keyVersion,3);});
test("wrong holder fails",()=>{const x=fixture();const d=evaluatePortableKeyRuntime({manifest:x.manifest,authorization:x.auth,encryptedObjectRef:x.ref,expectedHolderDid:"did:soul:holder-bob",expectedSubjectDid:sera,expectedKeyRef:keyRef,now:"2026-09-19T20:30:00Z",minimumKeyVersion:3});assert.equal(d.status,"FAIL");assert.ok(d.reasonCodes.includes("KEY_MANIFEST_HOLDER_MISMATCH"));});
test("rollback key version fails",()=>{const x=fixture();const d=evaluatePortableKeyRuntime({manifest:x.manifest,authorization:x.auth,encryptedObjectRef:x.ref,expectedHolderDid:holder,expectedSubjectDid:sera,expectedKeyRef:keyRef,now:"2026-09-19T20:30:00Z",minimumKeyVersion:4});assert.equal(d.status,"FAIL");assert.ok(d.reasonCodes.includes("KEY_MANIFEST_ROLLBACK_DETECTED"));});
test("CID substitution fails",()=>{const x=fixture();x.ref.cid="bafybeidifferentciphertext";const d=evaluatePortableKeyRuntime({manifest:x.manifest,authorization:x.auth,encryptedObjectRef:x.ref,expectedHolderDid:holder,expectedSubjectDid:sera,expectedKeyRef:keyRef,now:"2026-09-19T20:30:00Z",minimumKeyVersion:3});assert.equal(d.status,"FAIL");assert.ok(d.reasonCodes.includes("KEY_OBJECT_CID_MISMATCH"));});
test("expired SoulScan authorization fails",()=>{const x=fixture();const d=evaluatePortableKeyRuntime({manifest:x.manifest,authorization:x.auth,encryptedObjectRef:x.ref,expectedHolderDid:holder,expectedSubjectDid:sera,expectedKeyRef:keyRef,now:"2026-09-19T22:00:00Z",minimumKeyVersion:3});assert.equal(d.status,"FAIL");assert.ok(d.reasonCodes.includes("SOULSCAN_RECOVERY_AUTHORIZATION_EXPIRED"));});
