import test from "node:test";import assert from "node:assert/strict";import {createHash} from "node:crypto";
import {SoulScanAuthorizationClient,IpfsGatewayEncryptedKeyStore,StaticPortableKeyManifestResolver,PortableKeyRecoveryCoordinator,type KeyEnvelopeOpener} from "../../packages/portable-key-client/src/index.js";

const holder="did:soul:holder-alice";const sera="did:soul:agent:sera-alice";const keyRef="keyref:sera:1";const cid="bafyportableciphertext001";
const ciphertext=Buffer.from("encrypted-key-envelope","utf8");const ciphertextHash="sha256:"+createHash("sha256").update(ciphertext).digest("hex");
const manifest:any={schema:"ssw.portable-key-manifest.v1",manifest_id:"11111111-1111-4111-8111-111111111111",key_ref:keyRef,subject_did:sera,governing_holder_did:holder,key_class:"SERA_AGENT_SIGNING",key_version:2,encrypted_key_cid:cid,encryption_profile:"SOUL-ID-KEY-ENC-1",recovery_policy_ref:"recovery:soulscan",supersedes_manifest_id:null,status:"ACTIVE",created_at:"2026-09-19T20:00:00Z",expires_at:null,integrity:{manifest_hash:"sha256:"+"a".repeat(64),signature_ref:"sig:manifest"}};
const auth:any={schema:"ssw.soulscan-recovery-authorization.v1",authorization_id:"22222222-2222-4222-8222-222222222222",recovery_id:"33333333-3333-4333-8333-333333333333",holder_did:holder,sera_agent_did:sera,key_ref:keyRef,purpose:"SIGN",proof_class:"RP2",assurance_level:"RAL4",status:"PASS",issued_at:"2026-09-19T20:00:00Z",expires_at:"2026-09-19T21:00:00Z",verifier_ref:"soulscan:test",evidence_ref:"evidence:1",reason_codes:[],integrity:{authorization_hash:"sha256:"+"b".repeat(64),signature_ref:"sig:soulscan"}};
const ref:any={schema:"ssw.encrypted-key-object-ref.v1",key_ref:keyRef,cid,ciphertext_hash:ciphertextHash,encryption_profile:"SOUL-ID-KEY-ENC-1",key_version:2,subject_did:sera,governing_holder_did:holder,created_at:"2026-09-19T20:00:00Z"};

test("SoulScan client validates returned DID/key bindings",async()=>{const c=new SoulScanAuthorizationClient("https://soulscan.internal/authorize",{post:async()=>auth});const out=await c.authorize({holderDid:holder,seraAgentDid:sera,keyRef,purpose:"SIGN",recoveryId:auth.recovery_id});assert.equal(out.status,"PASS");});
test("IPFS key store verifies ciphertext hash",async()=>{const store=new IpfsGatewayEncryptedKeyStore("https://ipfs.example",async()=>({ok:true,status:200,arrayBuffer:async()=>ciphertext.buffer.slice(ciphertext.byteOffset,ciphertext.byteOffset+ciphertext.byteLength)}));const out=await store.fetch(ref);assert.equal(out.integrityHash,ciphertextHash);});
test("IPFS ciphertext substitution fails",async()=>{const bad=Buffer.from("different");const store=new IpfsGatewayEncryptedKeyStore("https://ipfs.example",async()=>({ok:true,status:200,arrayBuffer:async()=>bad.buffer.slice(bad.byteOffset,bad.byteOffset+bad.byteLength)}));await assert.rejects(()=>store.fetch(ref),/IPFS_KEY_OBJECT_HASH_MISMATCH/);});
test("portable recovery opens SERA signing session without device dependency",async()=>{const soulscan=new SoulScanAuthorizationClient("https://soulscan.internal/authorize",{post:async()=>auth});const ipfs=new IpfsGatewayEncryptedKeyStore("https://ipfs.example",async()=>({ok:true,status:200,arrayBuffer:async()=>ciphertext.buffer.slice(ciphertext.byteOffset,ciphertext.byteOffset+ciphertext.byteLength)}));let opened=false;const opener:KeyEnvelopeOpener={open:async()=>{opened=true;return{keyRef,subjectDid:sera,signDigest:async()=>({signature:new Uint8Array([1,2,3]),signatureFormat:"TEST",operationRef:"op:1"}),close:async()=>{}};}};const c=new PortableKeyRecoveryCoordinator(new StaticPortableKeyManifestResolver(new Map([[keyRef,manifest]])),soulscan,ipfs,opener);const session=await c.openSigningSession({holderDid:holder,seraAgentDid:sera,subjectDid:sera,keyRef,recoveryId:auth.recovery_id,encryptedObjectRef:ref,now:"2026-09-19T20:30:00Z",minimumKeyVersion:2});assert.equal(session.subjectDid,sera);assert.equal(opened,true);});
test("portable recovery rejects stale key version",async()=>{const soulscan=new SoulScanAuthorizationClient("https://soulscan.internal/authorize",{post:async()=>auth});const ipfs=new IpfsGatewayEncryptedKeyStore("https://ipfs.example",async()=>({ok:true,status:200,arrayBuffer:async()=>ciphertext.buffer.slice(ciphertext.byteOffset,ciphertext.byteOffset+ciphertext.byteLength)}));const opener:KeyEnvelopeOpener={open:async()=>{throw new Error("should not open");}};const c=new PortableKeyRecoveryCoordinator(new StaticPortableKeyManifestResolver(new Map([[keyRef,manifest]])),soulscan,ipfs,opener);await assert.rejects(()=>c.openSigningSession({holderDid:holder,seraAgentDid:sera,subjectDid:sera,keyRef,recoveryId:auth.recovery_id,encryptedObjectRef:ref,now:"2026-09-19T20:30:00Z",minimumKeyVersion:3}),/KEY_MANIFEST_ROLLBACK_DETECTED/);});
