import test from "node:test"; import assert from "node:assert/strict"; import {readFile} from "node:fs/promises";
import {buildPaymentSendAction} from "../../packages/action-contract-builder/src/index.js";
import {evaluateSessionEligibility,applyEligibilityToAction} from "../../packages/runtime-assurance/src/index.js";
async function fixture(){const intent=JSON.parse(await readFile(new URL("../fixtures/resolved-intent.payment-send.valid.json",import.meta.url),"utf8"));const b=buildPaymentSendAction(intent,{actionId:"88888888-8888-4888-8888-888888888888",saelCorrelationId:"99999999-9999-4999-8999-999999999999",idempotencyKey:"idempotency-001",replayToken:"replay-token-001",createdAt:"2026-09-19T16:01:00Z",expiresAt:"2026-09-19T16:10:00Z"});if(b.status!=="BUILT")throw new Error();return b.actionContract;}
const device={schema:"ssw.device-record.v1",device_id:"device:phone-001",holder_did:"did:soul:holder-alice",sera_agent_did:"did:soul:agent:sera-alice",device_type:"PHONE",platform:"ios",state:"TRUSTED",registered_at:"2026-09-19T15:00:00Z",last_attested_at:"2026-09-19T15:55:00Z",trust_expires_at:"2026-09-19T18:00:00Z",attestation_ref:"attestation:1",risk_flags:[]} as const;
const runtime={schema:"ssw.runtime-record.v1",runtime_id:"sera-runtime:phone-001",sera_agent_did:"did:soul:agent:sera-alice",device_id:"device:phone-001",runtime_class:"PRIMARY_PHONE",state:"ELIGIBLE",registered_at:"2026-09-19T15:00:00Z",session_id:"sera-session:1",session_expires_at:"2026-09-19T17:00:00Z",attestation_ref:"attestation:1"} as const;
const did="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
test("trusted device and eligible runtime qualify R3 payment",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device},runtime:{...runtime},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});assert.equal(d.status,"ELIGIBLE");});
test("registered device fails R3",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device,state:"REGISTERED"},runtime:{...runtime},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});assert.equal(d.status,"INELIGIBLE");});
test("revoked device fails",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device,state:"REVOKED"},runtime:{...runtime},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});assert.equal(d.status,"REVOKED");});
test("suspended runtime fails",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device},runtime:{...runtime,state:"SUSPENDED"},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});assert.equal(d.status,"SUSPENDED");});
test("expired session fails",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device},runtime:{...runtime,session_expires_at:"2026-09-19T16:00:00Z"},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});assert.equal(d.status,"EXPIRED");});
test("wrong holder fails",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device,holder_did:"did:soul:other"},runtime:{...runtime},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});assert.equal(d.status,"INELIGIBLE");});
test("eligibility application copies action",async()=>{const a=await fixture();const d=evaluateSessionEligibility({action:a,device:{...device},runtime:{...runtime},decisionId:did,evaluatedAt:"2026-09-19T16:05:00Z"});const next=applyEligibilityToAction(a,d);assert.equal(a.policy.device_eligible,false);assert.equal(next.policy.device_eligible,true);assert.equal(next.policy.runtime_eligible,true);});
