import test from "node:test";import assert from "node:assert/strict";import {evaluateVoiceSafety} from "../../packages/sera-voice-runtime/src/index.js";
const holder="did:soul:holder-alice",sera="did:soul:agent:sera-alice";
const signals={acoustic:.99,transcript:.99,holderAdaptation:.95,intent:.99,entity:.99,numeric:.99,negation:.99,context:.99,environment:.99};
const clear={protectedNumeric:false,recipient:false,asset:false,negation:false,multipleSpeakers:false};
test("V1 clear wallet read continues",()=>{const x=evaluateVoiceSafety({holderDid:holder,seraAgentDid:sera,riskClass:"V1",signals,ambiguity:clear,createdAt:"2026-09-19T21:00:00Z"});assert.equal((x as any).decision,"CONTINUE");});
test("V4 clear transaction requires independent authorization",()=>{const x=evaluateVoiceSafety({holderDid:holder,seraAgentDid:sera,riskClass:"V4",signals,ambiguity:clear,protectedNumericCandidates:["15"],createdAt:"2026-09-19T21:00:00Z"});assert.equal((x as any).decision,"REQUIRE_INDEPENDENT_AUTHORIZATION");});
test("15 versus 50 ambiguity clarifies",()=>{const x=evaluateVoiceSafety({holderDid:holder,seraAgentDid:sera,riskClass:"V3",signals,ambiguity:{...clear,protectedNumeric:true},protectedNumericCandidates:["15","50"],createdAt:"2026-09-19T21:00:00Z"});assert.equal((x as any).decision,"CLARIFY");assert.ok((x as any).reason_codes.includes("PROTECTED_NUMERIC_UNCERTAIN"));});
test("uncertain negation on consequential command stops",()=>{const x=evaluateVoiceSafety({holderDid:holder,seraAgentDid:sera,riskClass:"V4",signals:{...signals,negation:.6},ambiguity:{...clear,negation:true},protectedNumericCandidates:["500"],createdAt:"2026-09-19T21:00:00Z"});assert.equal((x as any).decision,"STOP");});
test("recipient ambiguity clarifies",()=>{const x=evaluateVoiceSafety({holderDid:holder,seraAgentDid:sera,riskClass:"V3",signals,ambiguity:{...clear,recipient:true},protectedNumericCandidates:["100"],createdAt:"2026-09-19T21:00:00Z"});assert.equal((x as any).decision,"CLARIFY");});
