import test from "node:test";import assert from "node:assert/strict";
import {DenyAllIdentityVerifier,JsonLogger,ReadinessRegistry,ServiceError,ServiceHost,StaticIdentityVerifier,loadRuntimeConfig,redactForLog} from "../../packages/service-host/src/index.js";

test("runtime config validates required service name",()=>{assert.throws(()=>loadRuntimeConfig({}),/SERVICE_NAME_REQUIRED/);const c=loadRuntimeConfig({SERVICE_NAME:"authority",SERVICE_PORT:"0",RUNTIME_ENVIRONMENT:"test"});assert.equal(c.port,0);assert.equal(c.environment,"test");});
test("logger redaction removes common secret classes",()=>{const out=redactForLog({token:"abc",nested:{private_key:"xyz",safe:"ok"}}) as any;assert.equal(out.token,"[REDACTED]");assert.equal(out.nested.private_key,"[REDACTED]");assert.equal(out.nested.safe,"ok");});
test("readiness is fail closed until dependencies are ready",()=>{const r=new ReadinessRegistry();r.register("database");assert.equal(r.snapshot().ready,false);r.set("database",true);assert.equal(r.snapshot().ready,true);});
test("service host exposes lifecycle health and identity-gated route",async()=>{const lines:string[]=[];const readiness=new ReadinessRegistry();readiness.register("control",true);const config=loadRuntimeConfig({SERVICE_NAME:"test-service",SERVICE_VERSION:"1.0.0",SERVICE_PORT:"0",RUNTIME_ENVIRONMENT:"test"});const host=new ServiceHost({config,readiness,logger:new JsonLogger(x=>lines.push(x)),identityVerifier:new StaticIdentityVerifier(new Set(["service:orchestrator"])),routes:[{method:"POST",path:"/internal/check",requireServiceIdentity:true,handler:({context})=>({status:200,body:{caller:context.callerIdentity}})}]});const bound=await host.start();try{const live=await fetch(`http://${bound.host}:${bound.port}/health/live`);assert.equal(live.status,200);const ready=await fetch(`http://${bound.host}:${bound.port}/health/ready`);assert.equal(ready.status,200);const denied=await fetch(`http://${bound.host}:${bound.port}/internal/check`,{method:"POST",body:"{}",headers:{"content-type":"application/json"}});assert.equal(denied.status,401);const allowed=await fetch(`http://${bound.host}:${bound.port}/internal/check`,{method:"POST",body:"{}",headers:{"content-type":"application/json","x-service-identity":"service:orchestrator"}});assert.equal(allowed.status,200);assert.equal((await allowed.json() as any).caller,"service:orchestrator");}finally{await host.stop();}assert.equal(host.lifecycle,"STOPPED");assert.ok(lines.length>0);});
test("default identity verifier denies asserted headers",async()=>{const config=loadRuntimeConfig({SERVICE_NAME:"deny-test",SERVICE_PORT:"0",RUNTIME_ENVIRONMENT:"test"});const host=new ServiceHost({config,identityVerifier:new DenyAllIdentityVerifier(),logger:new JsonLogger(()=>{}),routes:[{method:"POST",path:"/private",requireServiceIdentity:true,handler:()=>({status:200,body:{ok:true}})}]});const bound=await host.start();try{const res=await fetch(`http://${bound.host}:${bound.port}/private`,{method:"POST",body:"{}",headers:{"x-service-identity":"service:any"}});assert.equal(res.status,401);}finally{await host.stop();}});
test("typed error body does not expose stack or message",()=>{const e=new ServiceError("DEVICE_NOT_ELIGIBLE","AUTHORIZATION",false,403);assert.equal(e.code,"DEVICE_NOT_ELIGIBLE");});
